from src.data_prediction.yolo_predictions_and_distance_estimation import ObjectDetection_and_Distance_Estimation


detector_and_distance_estimation = ObjectDetection_and_Distance_Estimation(capture_index=1)
detector_and_distance_estimation()
